/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedLinkRouteImport } from './routes/_authenticated/link'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord/start'
import { Route as ApiPublicAuthRobloxCallbackRouteImport } from './routes/api/public/auth/roblox/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLinkRoute = AuthenticatedLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordStartRoute =
  ApiPublicAuthDiscordStartRouteImport.update({
    id: '/api/public/auth/discord/start',
    path: '/api/public/auth/discord/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthRobloxCallbackRoute =
  ApiPublicAuthRobloxCallbackRouteImport.update({
    id: '/api/public/auth/roblox/callback',
    path: '/api/public/auth/roblox/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/link': typeof AuthenticatedLinkRoute
  '/live': typeof AuthenticatedLiveRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/link': typeof AuthenticatedLinkRoute
  '/live': typeof AuthenticatedLiveRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/link': typeof AuthenticatedLinkRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/link'
    | '/live'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/link'
    | '/live'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/link'
    | '/_authenticated/live'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordStartRoute: typeof ApiPublicAuthDiscordStartRoute
  ApiPublicAuthRobloxCallbackRoute: typeof ApiPublicAuthRobloxCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/link': {
      id: '/_authenticated/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AuthenticatedLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/start': {
      id: '/api/public/auth/discord/start'
      path: '/api/public/auth/discord/start'
      fullPath: '/api/public/auth/discord/start'
      preLoaderRoute: typeof ApiPublicAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/roblox/callback': {
      id: '/api/public/auth/roblox/callback'
      path: '/api/public/auth/roblox/callback'
      fullPath: '/api/public/auth/roblox/callback'
      preLoaderRoute: typeof ApiPublicAuthRobloxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLinkRoute: typeof AuthenticatedLinkRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLinkRoute: AuthenticatedLinkRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordStartRoute: ApiPublicAuthDiscordStartRoute,
  ApiPublicAuthRobloxCallbackRoute: ApiPublicAuthRobloxCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
