/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPositionsRouteImport } from './routes/api/public/positions'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord/start'
import { Route as ApiPublicAuthRobloxCallbackRouteImport } from './routes/api/public/auth/roblox/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPositionsRoute = ApiPublicPositionsRouteImport.update({
  id: '/api/public/positions',
  path: '/api/public/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordStartRoute =
  ApiPublicAuthDiscordStartRouteImport.update({
    id: '/api/public/auth/discord/start',
    path: '/api/public/auth/discord/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthRobloxCallbackRoute =
  ApiPublicAuthRobloxCallbackRouteImport.update({
    id: '/api/public/auth/roblox/callback',
    path: '/api/public/auth/roblox/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/auth/roblox/callback': typeof ApiPublicAuthRobloxCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/positions'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/positions'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  id:
    | '__root__'
    | '/'
    | '/api/public/positions'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/auth/roblox/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPositionsRoute: typeof ApiPublicPositionsRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordStartRoute: typeof ApiPublicAuthDiscordStartRoute
  ApiPublicAuthRobloxCallbackRoute: typeof ApiPublicAuthRobloxCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/positions': {
      id: '/api/public/positions'
      path: '/api/public/positions'
      fullPath: '/api/public/positions'
      preLoaderRoute: typeof ApiPublicPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/start': {
      id: '/api/public/auth/discord/start'
      path: '/api/public/auth/discord/start'
      fullPath: '/api/public/auth/discord/start'
      preLoaderRoute: typeof ApiPublicAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/roblox/callback': {
      id: '/api/public/auth/roblox/callback'
      path: '/api/public/auth/roblox/callback'
      fullPath: '/api/public/auth/roblox/callback'
      preLoaderRoute: typeof ApiPublicAuthRobloxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPositionsRoute: ApiPublicPositionsRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordStartRoute: ApiPublicAuthDiscordStartRoute,
  ApiPublicAuthRobloxCallbackRoute: ApiPublicAuthRobloxCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
